// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD01yj4wUsVLihT_fWcSH5Zoyxgo5yF-EU',
    appId: '1:587231571634:android:217c3cdd7fdc57aac1e3ab',
    messagingSenderId: '587231571634',
    projectId: 'ima-app-173da',
    storageBucket: 'ima-app-173da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAozBhAYjpUA09YlgGwfFqXTR2lZl_dIvs',
    appId: '1:587231571634:ios:492b1d22f38e46f5c1e3ab',
    messagingSenderId: '587231571634',
    projectId: 'ima-app-173da',
    storageBucket: 'ima-app-173da.appspot.com',
    androidClientId:
        '587231571634-gtd4ursn1tkr4kf0c2vvmjg29ub5qfmm.apps.googleusercontent.com',
    iosClientId:
        '587231571634-tnjjra2ialg1fgp095p03cpt3dlqe0fb.apps.googleusercontent.com',
    iosBundleId: 'com.imafv.medapp ',
  );
}
